# 应用服务 WEB 访问端口
server:
  port: 8081
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peripheral?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=TRUE
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    # lettuce 连接池配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 6


# 日志配置
logging:
  level:
    com.tiam.peripheral: debug
# Mybatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.tiam.peripheral.entity
  mapper-locations: classpath:mapper/*.xml
  # sql 打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









