# 应用服务 WEB 访问端口
server:
  port: 8080
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peripheral?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

# 日志配置
logging:
  level:
    org.springframework: info
# Mybatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.tiam.peripheral.entity
  mapper-locations: classpath:mapper/*.xml









